version: "3"

services:
    ampache:
        build: ampache
        image: ampache_config
        container_name: ampache_config1
        environment:
            - AMPACHE_DB_HOST=mariadb
            - AMPACHE_DB_USERNAME=${AMPACHE_DB_USERNAME}
            - AMPACHE_DB_PASSWORD=${AMPACHE_DB_PASSWORD}
        volumes:
            # - /srv/docker_volumes/ampache/config:/var/www/config
            - /srv/docker_volumes/ampache/config:/var/www/config1
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
            - "80:80"
        depends_on:
            - mariadb

    mariadb:
        # build: mariadb
        # image: owncloud_mariadb
        image: webhippie/mariadb:latest
        container_name: owncloud_mariadb1
        environment:
            - MARIADB_ROOT_PASSWORD=owncloud
            - MARIADB_USERNAME=owncloud
            - MARIADB_PASSWORD=owncloud
            - MARIADB_DATABASE=owncloud
            - MARIADB_MAX_ALLOWED_PACKET=128M
            - MARIADB_INNODB_LOG_FILE_SIZE=64M
            - MARIADB_INNODB_LARGE_PREFIX=ON
            - MARIADB_INNODB_FILE_FORMAT=Barracuda
        volumes:
            - /srv/docker_volumes/mysql:/var/lib/mysql
