version: "3"

services:
    ampache:
        build: ampache
        image: ampache_config
        container_name: ampache_config1
        environment:
            - AMPACHE_DB_HOSTNAME=mariadb
            - AMPACHE_DB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - AMPACHE_DB_USERNAME=${MARIADB_USERNAME}
            - AMPACHE_DB_PASSWORD=${MARIADB_PASSWORD}
            - AMPACHE_DB_NAME=${MARIADB_DATABASE}
            - AMPACHE_SECRET_KEY=${AMPACHE_SECRET_KEY}
        volumes:
            # - /srv/docker_volumes/ampache/config:/var/www/config
            - /srv/docker_volumes/ampache/config:/var/www/config1
            # - /etc/localtime:/etc/localtime:ro
            # - /etc/timezone:/etc/timezone:ro
        ports:
            - "80:80"
        depends_on:
            - mariadb

    mariadb:
        # build: mariadb
        # image: owncloud_mariadb
        image: webhippie/mariadb:latest
        container_name: ampache_mariadb1
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_USERNAME=${MARIADB_USERNAME}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_MAX_ALLOWED_PACKET=128M
            - MARIADB_INNODB_LOG_FILE_SIZE=64M
            - MARIADB_INNODB_LARGE_PREFIX=ON
            - MARIADB_INNODB_FILE_FORMAT=Barracuda
        volumes:
            - /srv/docker_volumes/mariadb:/var/lib/mysql
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
